version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=mysql-db
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 30s
      retries: 5
    volumes:
      - ./devjs_data:/var/lib/mysql_db
      - "./bd-scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - network-app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jeancbsan/app:v1
    container_name: app
    tty: true
    ports:
      - "8090:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network-app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - network-app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - network-app

networks:
  network-app:
    driver: bridge