version: "2.4"
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/cayena?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
services:
  mysqldb:
    image: mysql
    container_name: database
    networks:
      - app.network
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    mem_limit: 256m
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: app-backend
    image: jeancbsan/products-cayena:0.0.1-SNAPSHOT
    networks:
      - app.network
    ports:
      - 8080:8080
    environment:
      <<: *database-variables
    mem_limit: 512m
    depends_on:
      - mysqldb
volumes:
  db_data:

networks:
  app.network:
    driver: bridge